"""Centralized UI strings to avoid hard-coded text and support localization."""

UI_STRINGS = {
    # Authentication & Login UI
    "login_brand_name": "PAL'S OI Tracker",
    "login_brand_tagline": "Sign in to access your dashboard",
    "login_user_id_label": "User ID",
    "login_user_id_placeholder": "Enter User ID",
    "login_password_label": "Password",
    "login_password_placeholder": "Enter Password",
    "login_totp_label": "2FA Code",
    "login_totp_placeholder": "Enter 6-digit code",
    "login_totp_help": "Enter the 6-digit code from your authenticator app or SMS.",
    "login_submit_label": "Sign In",
    "login_initializing_notice": "System is starting up. This may take a minute...",
    "login_footer_text": "Your credentials are only used locally to create a secure session.",
    "login_error_unauthorized": "Please sign in to continue.",
    "login_error_initializing": "System is still initializing. Please wait.",
    "login_error_initializing_in_progress": "Initialization already in progress. Please wait a moment.",
    "login_error_missing_fields": "Please provide User ID and Password.",
    "login_error_missing_totp": "Two-factor code is required.",
    "login_error_auth_failed": "Unable to authenticate with Zerodha. Please verify your credentials and TOTP.",
    "login_error_invalid_creds": "Invalid credentials.",
    "logout_button_label": "Exit",
    "logout_button_tooltip": "Sign out and return to login page",

    "info_bar_vix_label": "VIX",
    "table_iv_header": "IV(%)",
    "table_pct_change_3m": "OI %CHG (3M)",
    "table_diff_header": "DIFF",
    "info_bar_itm_ce_label": "ITM CE Δ%",
    "info_bar_itm_pe_label": "ITM PE Δ%",
    "info_bar_future_symbol_label": "Future",
    "info_bar_future_price_label": "Fut Price",
    "info_bar_future_oi_label": "Fut OI",
    "info_bar_future_oi_change_label": "Fut OI Δ% (3M)",
    "survivor_feed_namespace": "/survivor_feed",
    "survivor_feed_event": "tick",
    "survivor_feed_symbol_nifty": "NSE:NIFTY 50",
    "survivor_feed_symbol_sensex": "BSE:SENSEX",
    "survivor_feed_error_not_found": "Latest price unavailable for the requested symbol.",
    "survivor_feed_error_exchange": "Unsupported exchange in symbol.",
    "init_underlying_ltp": "Initial {symbol} LTP: {price}",

    # NEW ML STRINGS
    "ml_banner_signal_label": "ML Signal",
    "ml_banner_confidence_label": "Confidence",
    "ml_regime_label": "Regime",
    "ml_position_size_label": "Risk Fraction",
    "ml_kelly_label": "Kelly %",
    "ml_lots_label": "Lots",
    "ml_signal_history_label": "Recent Signals",

    # Monitoring / Navigation
    "nav_monitoring_label": "Model Health",
    "monitoring_title": "Model Monitoring Dashboard",
    "monitoring_subtitle": "Live view of training diagnostics & CV metrics",
    "monitoring_card_cv": "Time-Series CV",
    "monitoring_card_target": "Target Distribution",
    "monitoring_card_optuna": "Optuna Best Params",
    "monitoring_card_auto_ml": "Walk-Forward AutoML",
    "monitoring_card_backtest": "Backtest Snapshot",
    "monitoring_card_online": "Online Learning",
    "monitoring_updated_label": "Last Updated",
    "monitoring_drawdown_label": "Equity & Drawdown",
    "monitoring_accuracy_label": "Rolling Accuracy",
    "monitoring_walkforward_label": "Walk-Forward Segments"
}